### ISSUE TITLE
Drift between docs and latest release

### ISSUE THREAD

**Issue by nholden** [inertiajs/inertia-rails#169]
I tried to install Inertia on a new Rails app today and bumped into lots of friction. I tried following the [server-side setup](https://inertia-rails.dev/guide/server-side-setup) documents, but `bin/rails generate inertia:install` didn't work, and I ran into an error about needing to use webpacker when I ran `bin/rails generate inertia_rails:install`.

It looks like https://github.com/inertiajs/inertia-rails/pull/158 introduced changes to the docs and installers, but there hasn't been a new release of inertia-rails yet. It seems like there should be a new version released or a revert to the docs changes.

Updating my gemfile to look like this worked as a workaround:

```
gem "inertia_rails", github: "inertiajs/inertia-rails", ref: "65ba636cc0b351b1d8ece9e353e746e32f7bf391"
```

**Comment by bknoles** [comment]
Hey @nholden you diagnosed things correctly! The docs are currently releasing before gem releases.

I just cut a `3.5.0` release, so the docs now match the current release.

Separately, we'll make a change to prevent the drift in the future. Easiest thing is probably to deploy docs when a tag is pushed (instead of a push to master), but we've also talked about adding more automation around releases. We'll aim to resolve it before merging any more changes to the docs.

DX is really important to us, so thanks for reporting this really rough edge so that we can fix it for everyone!

**Comment by nholden** [comment]
Thank you, @bknoles! Appreciate your thoughtfulness around DX.

Tying doc releases to tags and adding more automation around releases both sound like great approaches. Another thing to consider is versioning docs similar to how the [Rails Guides](https://guides.rubyonrails.org/) work with [Edge Guides](https://edgeguides.rubyonrails.org/) for the main branch.
