### ISSUE TITLE
Automatically share validation errors

### ISSUE THREAD

**Issue by reinink** [inertiajs/inertia-rails#47]
Hey there folks! Thanks so much for your ongoing maintenance of this adapter. ❤️ 

I recently updated the Laravel adapter to automatically share validation errors. You can read more about that in the release notes [here](https://github.com/inertiajs/inertia-laravel/releases/tag/v0.2.9).

Would it makes sense do add this kind of functionality to the Rails adapter as well? 🤔

**Comment by BrandonShar** [comment]
An issue from the captain himself! 😄 

Thanks for the heads up @reinink, we'll take a look this week and see; my first instinct is that it will fit in just fine.

**Comment by reinink** [comment]
Awesome. It really just needs to fit with how you do error validation in Rails. With Laravel, it goes like this:

1. You submit the form via `Inertia.post()`
2. Laravel runs the validation
3. On success (no errors), things just carry on.
4. On failure (validation errors), Laravel automatically redirects back to the submitting page, with the errors flashed (in the session).
5. In a "normal" Laravel app those errors are then made available automatically to the Blade views. However, with Inertia, you need to `Inertia::share()` them, which the Laravel adapter now automatically does.
6. Those errors are returned back to the form page (as props, which are reactive), and you're able to display them.

Is the process similar in Rails?

**Comment by bknoles** [comment]
Rails differs from Laravel pretty significantly in the way it handles validations. In Laravel, they are handled at the controller level, while in Rails validations are defined and attached to models. (someone correct me if I'm wrong on the Laravel side... i'm more familiar with Rails).

So, in a typical Rails use case, validation errors are already automagically sent to the frontend. Something like:

```ruby
render inertia: 'MyPageComponent', props: { myThing: @my_active_modely_thing }
```

will have an array of errors on `myThing` (if ActiveModel validations have failed).

That said, maybe a closer Rails equivalent to the Laravel error bags is flash messages? They are defined at the controller level, and can include things like an arbitrary error message in `flash[:error]`. I know Brandon wired flash messages up using "Inertia share" in our Inertia-fied app.

Questions:

1. @BrandonShar Would you say the flash messages are a close analog of Laravel validation errors? (I ask because you are really familiar with both frameworks)
2. @ everyone: If we automatically share validations are in the Laravel adapter, but automatically share flash messages in the Rails adapter, is that behavior different enough to say "maybe we shouldn't share flash messages in Rails"?

**Comment by reinink** [comment]
Yeah, I'm sort of familiar with how Rails does validation, and I understand that it happens at the model level, not the controller level, and that's totally fine...they don't have to be the same. What I'm more interested in is this part:

> So, in a typical Rails use case, validation errors are already automagically sent to the frontend.

So, if I'm understanding you correctly, when you're display errors in your templates, you reference those errors via the model, and not some generic `errors` variable? If that's the case, that does make things a little more tricky to do in an automated way like it's done in Laravel. Maybe it just doesn't even make sense for the Rails adapter at that point.

As for Laravel and flash messages, yes, the errors are basically a type of flash message, but they are specific to error handling. In the Laravel adapter we automatically share the validation errors, but not flash messages.

**Comment by bknoles** [comment]
yea, exactly... to follow onto the code above, using React, I would reference the errors something like:

```jsx
// omitting the state management/submission for simplicity
const MyPageComponent = ({ myThing }) => (
  <div>
    <label for="attribute">Attribute</label>
    <input type="text" name="attribute" defaultValue={myThing.attribute) />
    {myThing?.errors?.attribute && (
      <p className="error-text-of-some-kind">
        Attribute {myThing.errors.join(" and ")}
      </p>
    )}
  </div>
);

```

but, it's also common for a non-model-specific error to go in the flash messages, like if authorization fails or something like that.

if the Rails adapter included all the flash messages by default, would that diverge from the Laravel adapter in a way that felt confusing or unsatisfying? we could also just share just the `flash[:error]`, but that would (subjectively) feel less "Rails-y" to me.

**Comment by BrandonShar** [comment]
A very similar topic is being discussed here: https://github.com/inertiajs/inertiajs.com/pull/31

**Comment by BilalBudhani** [comment]
I'm quoting multiple comments from above and replying them inline. 

> So, if I'm understanding you correctly, when you're display errors in your templates, you reference those errors via the model, and not some generic errors variable? 

Yes, this is the standard way of handling errors in Rails. The Model object is passed to the view for displaying errors. There is no main `error` variable available in the request to make use of.

**Comment by bknoles** [comment]
i've done an about face on my initial comments here... #50 will bake a pattern into the gem which is quite similar AFAICT to what happens in the Laravel library.
