### ISSUE TITLE
Making CSRF protection work out of the box

### ISSUE THREAD

**Issue by buhrmi** [inertiajs/inertia-rails#71]
At the moment, [manual steps](https://discord.com/channels/592327939920494592/759114256817455145/773925412626628618) are required to make CSRF protection work with Rails and Inertia.

To make CSRF protection work out of the box I'm proposing to add the following to the inertia-rails adapter:
1. Make every non-inertia request also send the current csrf token in a `XSRF-TOKEN` cookie, that will automatically be picked up by Axios.
2. Overwrite the [`request_authenticity_tokens`](https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L302) method to also check the `X-XSRF-TOKEN` header value (in addition to the `X-CSRF-TOKEN` header), since that is what Axios sends by default.

**Comment by BrandonShar** [comment]
Per this comment on the linked PR (https://github.com/inertiajs/inertia-rails/pull/72#issuecomment-941298861) I believe we decided that this wasn't necessary and is somewhat out of scope for Inertia.

As such, I'm going to close this issue, but please reopen if I've misunderstood!

**Comment by bknoles** [comment]
I'm going to reopen this issue. Our workaround, which was to add the CSRF token to an `X-CSRF-Token` header in the axios defaults ([see here](https://github.com/inertiajs/inertia-rails/blob/master/lib/generators/inertia_rails/install/react/inertia.jsx#L12)), fails to work on certain projects. I finally figured out why.

The workaround requires that NPM/yarn imports the axios package from inertia's dependencies. If axios is installed somewhere else in the dependency tree, and NPM/yarn imports that instance instead of the one that comes with Inertia, then Inertia requests will never set the `X-CSRF-Token` header. I realized this because CSRF stopped working after I installed axios as an explicit dependency (because ESLint was yelling at me about it).

The solution I added to the app was almost the same as @buhrmi 's original one. I added the `XSRF-Token` cookie in a controller hook. Axios will grab this cookie and send it with all requests. But instead of overwriting the `request_authenticity_tokens` method, I added middleware that copies an `X-XSRF-Token` header (which Axios sends) into an `X-CSRF-Token` header (which Rails looks for). I like this better than monkey patching, but I'm open to hear any downsides I haven't thought of.

Rereading the conversation here and in the PR, skipping CSRF on inertia requests is super clever. So clever it makes me nervous 😅. I suppose the only failure mode there would be some browser deciding to go way off script sending requests, but since the cookie/header combo is so lightweight I'd rather be safe than sorry.

I'll put a PR together this week!

**Comment by mstallmo** [comment]
@bknoles thank you so much for the PR on this! I was just banging my head against this exact issue in a sign-in, sign-out flow with Devise in my app and the implementation in your PR worked like a charm! ❤️ 🚀

**Comment by mstallmo** [comment]
Also for anyone who stumbles across this before the PR is merged here is the concern that I wrote that mimics the behavior in the PR.

```ruby
module InertiaRequestProtectable
  extend ActiveSupport::Concern

  included do
    prepend_before_action do
      request.headers["HTTP_X_CSRF_TOKEN"] = request.headers[
        "HTTP_X_XSRF_TOKEN"
      ] if request.headers["HTTP_X_XSRF_TOKEN"] && request.headers["X-Inertia"]
    end

    after_action do
      cookies[
        "XSRF-TOKEN"
      ] = form_authenticity_token if protect_against_forgery?
    end
  end
end
```
